name: ML Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Train the model
        run: |
          python src/train.py

      - name: Run tests
        run: |
          pytest tests/

      - name: Upload trained model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: src/model.pkl
